### ISSUE TITLE
那个多行字符串的插件要怎么用呢？

### ISSUE THREAD

**Issue by YaoZihuan** [11039850/monalisa-db#1]
rt，能录个视频教程？

**Comment by 11039850** [comment]
首页有个关于插件使用的视频([Youtube](http://www.youtube.com/watch?v=3qpr0J7D7cQ) 和[优酷](http://v.youku.com/v_show/id_XMTU0ODk1MzA2MA==.html) ).  
    插件安装后，数据库模型代码的生成 和  SQL查询结果类的代码生成需要设置插件,  但是多行字符串不需要任何设置， 直接按这里的 [语法](/11039850/monalisa-db/wiki/Multiple-line%20syntax) 书写就可以了. 

    为了方便书写， 视频里在Eclipse中设置了Java编辑模板命名为mline， 这样只需要在Java编辑器下输入 mline ，就会自动插入多行语法， 很方便。 

    模板的设置方法： Windows->Preferences->Java->Editor->Templates  在右边new一个name为： mline， 内容为： ""/**~{${cursor}}*/
